config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Root route
  root 'users#home'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'logout', to: 'devise/sessions#destroy'
  end
  # Admin dashboard route
  get 'admin_dashboard', to: 'users#admin_dashboard', as: 'admin_dashboard'
  get 'user_dashboard', to: 'users#user_dashboard', as: 'user_dashboard'
  get 'admin_checkin', to: 'users#admin_checkin', as: 'admin_checkin'
  get 'user_checkin', to: 'users#user_checkin', as: 'user_checkin'
  post 'admin_checkin', to: 'users#admin_checkin'
  post 'user_checkin', to: 'users#checkin'
  post 'add_admin', to: 'users#add_admin', as: 'admin_add_admin'
  get '/users/home', to: 'users#home', as: 'users_home'
  get '/events/index', to: 'events#index', as: 'events_index'
  get '/events/new', to: 'events#new', as: 'events_new'

  get 'profile_setup', to: 'users#profile_setup'
  post 'create_profile', to: 'users#create_profile'

  get 'users/events_attended', to: 'users#events_attended', as: 'events_attended'
  get 'users/upcoming_events', to: 'users#upcoming_events', as: 'upcoming_events'

  # Users routes
  resources :users, except: :show do
    collection do
      put :grant_admin
      get 'profile_setup'
      post 'create_profile'
    end

    member do
      post 'checkin'
    end
    post 'add_admin', on: :collection
  end

  # Events routes
  resources :events, only: %i[index new create destroy]

  # Routes for Final Countdown Event
  get 'events/new_final_countdown', to: 'events#new_final_countdown', as: 'new_final_countdown_event'
  post 'events/create_final_countdown', to: 'events#create_final_countdown', as: 'create_final_countdown_event'
  resources :events, only: %i[index show new create destroy]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  belongs_to :classification
  has_many :events_users
  has_many :events, through: :events_users
  has_many :attended_events, through: :events_users, source: :event
  validates :classification, presence: true, on: :update_profile

  devise :omniauthable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.full_name = auth.info.name
      user.avatar_url = auth.info.image
      user.save(validate: false)  # Save without validation for now
    end
  end

  def is_admin?
    isAdmin
  end

  def self.from_omniauth(auth)
    where(email: auth['info']['email']).first_or_create
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
      user = User.from_omniauth(auth)
      if user.persisted?
        # The following if statement prevents non-tamu emails from logging in
        unless auth.info.email.ends_with?('@tamu.edu')
          # redirect_to after_sign_out_path_for(user), alert: 'Only @tamu.edu email addresses are allowed.' and return
          # # In your sign out action
          flash[:alert] = 'ONLY @TAMU.EDU EMAIL ADDRESSES ARE ALLOWED'
          redirect_to after_sign_out_path_for(user)
          return
        end
        # the following notifies the user of a successful login and redirects them to the correct page
        flash[:success] = I18n.t('devise.omniauth_callbacks.success', kind: 'Google')
        sign_in user, event: :authentication
        redirect_to after_sign_in_path_for(user)
        tempUser = User.find_by(email: user.email)
        session[:user_email] = auth.info.email
        # Checks if user exists and creates a new one if they do not
        if tempUser
          session[:user_email] = auth.info.email
        else
          session[:new_user] = true
          session[:user_email] = auth.info.email
          User.create!(
            first_name: auth.info.first_name,
            last_name: auth.info.last_name,
            email: auth.info.email,
            isAdmin: false,
            provider: auth.provider,
            uid: auth.uid,
            avatar_url: auth.info.avatar_url,
            password: 'password',
            phone_number: ""
          )
        end
      # redirects new users to a profile set up page
      else
        session[:google_data] = user_data_from_auth
        redirect_to profile_setup_path
      end
    end

    protected

    # function to redirct on a failed log in
    def after_omniauth_failure_path_for(_scope)
      new_user_session_path
    end

    private

    def auth
      @auth ||= request.env['omniauth.auth']
    end

    def user_data_from_auth
      {
        first_name: auth.info.first_name,
        last_name: auth.info.last_name,
        email: auth.info.email,
        provider: auth.provider,
        uid: auth.uid,
        avatar_url: auth.info.image,
        password: Devise.friendly_token[0, 20]
      }
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    def update_resource(resource, params)
      if resource.provider == 'google_oauth2'
        params.delete('current_password')
        resource.password = params['password']

        resource.update_without_password(params)
      else
        resource.update_with_password(params)
      end
    end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    def destroy
      revoke_google_oauth_token
      super # This will handle the regular logout process for Devise
    end

    def after_sign_out_path_for(_resource_or_scope)
      new_user_session_path
    end

    def after_sign_in_path_for(resource)
      if resource.isAdmin?
        admin_dashboard_path
      else
        user_dashboard_path
      end
    end

    private

    def revoke_google_oauth_token
      return unless session[:user_email].present?

      user_email = session[:user_email]
      user = User.find_by(email: user_email)
      user.update(google_oauth_token: nil) if user && user.google_oauth_token.present?

      session.delete(:user_email)
    end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  # before_action :ensure_admin, only: [:admin_dashboard, :grant_admin]
  before_action :redirect_new_users_to_profile_setup, only: :user_dashboard
  def home; end

  def admin_dashboard
    @users = User.all
    @events = Event.all
  end

  def user_dashboard
    @events = Event.all
    @final_countdown_date = Event.find_by(hasCountdown: true)&.date
    @current_user = User.find_by(email: session[:user_email])
  end

  def redirect_new_users_to_profile_setup
    return unless session[:new_user]

    redirect_to profile_setup_path
  end

  def checkin
    @events = Event.all
    @test = current_user

    return unless request.post?

    event = Event.find_by(id: params[:event_id])
    user = User.find_by(email: session[:user_email])

    # checks if user exists, if they dont they will be redirected to log in again
    redirect_to new_user_session_path and return if user.nil?

    # Check if phone numbers match
    if user.phone_number != params[:phone_number]
      redirect_to user_dashboard_path
      flash[:alert] = 'Phone number verification failed.'
      return
    end

    if event
      EventsUser.create(user_id: user.id, event_id: event.id)
      redirect_to user_dashboard_path, notice: 'Successfully checked-in!'

    else
      redirect_to user_dashboard_path
      flash[:alert] = 'Event not found with the specified ID.'
    end
  end

  def add_admin
    email = params[:email]
    user = User.find_by(email:)

    if user
      user.update(isAdmin: true)
      redirect_to admin_dashboard_path, notice: "#{user.email} has been granted admin status."
    else
      redirect_to admin_dashboard_path, alert: "User with email #{email} not found."
    end
  end

  def admin_checkin
    return unless request.post?

    first_name = params[:first_name]
    last_name = params[:last_name]
    email = params[:email]

    user = User.find_by(first_name:, last_name:, email:)

    if user
      userId = user.id
      EventsUser.create(user_id: userId, event_id: params[:event_id])
      redirect_to admin_dashboard_path
      flash[:notice] = 'User checked in successfully.'
    else
      redirect_to admin_checkin_path
      flash[:alert] = 'No user found with the specified first name, last name, and email.'
    end
  end

  def profile_setup
    @google_data = session[:google_data]
    @user = User.new
    @classifications = Classification.all
  end

  def create_profile
    google_data = session.delete(:google_data)

    user = User.new(google_data)
    user.phone_number = user_params[:phone_number]
    user.classification_id = user_params[:classification_id]
    # This part is for testing purposes
    user.email = "new_user@signedin.test" if user.email.blank?
    user.password = "test123" if user.password.blank?

    if user.save
      sign_in(user)
      redirect_to user_dashboard_path, notice: 'Profile created successfully.'
    else
      @user = user
      @classifications = Classification.all
      flash[:alert] = 'Error creating your profile. Please try again.'
      puts user.errors.full_messages
      render :profile_setup
    end
  end

  def events_attended
    @user = User.find_by(email: session[:user_email])

    # makes sure current stored user email is valid, otherwise user is redirected to log in again
    if @user
      @attended_events = @user.events
    else
      redirect_to new_user_session_path
    end
  end

  def upcoming_events
    @events = Event.where("date >= ?", Date.current).order(:date)
  end

  private

  def user_params
    params.require(:user).permit(:phone_number, :classification_id)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/admin_dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="<%= asset_path('admin_dash.css') %>">
    <link rel="stylesheet" type="text/css" href="<%= asset_path('flash_alert.css') %>">
    <title>Admin Dashboard</title>
</head>
<body>
<% flash.each do |type, message| %>
    <div class="flash-message <%= type %>">
    <%= message %>
    </div>
<% end %>
<header class="header">
    <div class="logo-and-title">
        <div class="logo">
            <img src="<%= asset_path('IMG_6562.png') %>" alt="logo" class="logo-icon">
        </div>
        <p class="title">Volunteers Around the World</p>
    </div>
    <h1 class="maintitle">Admin Dashboard</h1> 
    <%= link_to "Log Out", logout_path, class: "logout-button" %>
</header>

            <div class="bottom-left-container">
            <%= link_to user_dashboard_path , class: "user-button bottom-left-link" do %>
                <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com/ License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M502.6 278.6c12.5-12.5 12.5-32.8 0-45.3l-128-128c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L402.7 224 192 224c-17.7 0-32 14.3-32 32s14.3 32 32 32l210.7 0-73.4 73.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l128-128zM160 96c17.7 0 32-14.3 32-32s-14.3-32-32-32L96 32C43 32 0 75 0 128L0 384c0 53 43 96 96 96l64 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-64 0c-17.7 0-32-14.3-32-32l0-256c0-17.7 14.3-32 32-32l64 0z"/></svg>
                User Dashboard
                <% end %>
            </div>
         <div class="horizontal-container">

    <!-- Form to grant admin status by email -->
    <div class="section">
        <%= form_with(url: add_admin_users_path, method: :post, local: true) do |f| %>
          <%= f.label :email, "Enter Email:" %>
          <%= f.text_field :email %>
          <%= f.submit "Grant Admin Status" %>
          <% end %>

          <!-- Current Admins Section -->
          <h2>Current Admins</h2>
          <div class="scrollable-table">
              <table class="events-table">
                  <thead>
                      <tr>
                          <th>Email</th>
                      </tr>
                  </thead>
                  <tbody>
                      <% if @users.any? { |user| user.isAdmin? } %>
                          <% @users.each do |user| %>
                              <% if user.isAdmin? %>
                                  <tr>
                                      <td><%= user.email %></td>
                                  </tr>
                              <% end %>
                          <% end %>
                      <% else %>
                          <tr>
                              <td>There aren't any current admins.</td>
                          </tr>
                      <% end %>
                  </tbody>
              </table>
              </div>
          </div>


    <div class="vertical-container">
        <!-- Manually Check-In a User Section -->
        <div class="section checkin-section">
            <h3>
                <a href="<%= admin_checkin_path %>" class="check-in-button">
                <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 640 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#ffffff}</style><path d="M96 128a128 128 0 1 1 256 0A128 128 0 1 1 96 128zM0 482.3C0 383.8 79.8 304 178.3 304h91.4C368.2 304 448 383.8 448 482.3c0 16.4-13.3 29.7-29.7 29.7H29.7C13.3 512 0 498.7 0 482.3zM504 312V248H440c-13.3 0-24-10.7-24-24s10.7-24 24-24h64V136c0-13.3 10.7-24 24-24s24 10.7 24 24v64h64c13.3 0 24 10.7 24 24s-10.7 24-24 24H552v64c0 13.3-10.7 24-24 24s-24-10.7-24-24z"/></svg> Manually Check-In User
                </a>
            </h3>
        </div>
        <!-- User Information Section -->
        <div class="section user-info-section">
            <h2>Current Users</h2>
            <div class="scrollable-table">
            <table class="user-table">
                <thead>
                    <tr>
                        <th>Email</th>
                        <th>Phone Number</th>
                        <th>Major</th>
                    </tr>
                </thead>
                <tbody>
                    <% @users.each_with_index do |user, index| %>
                        <tr class="<%= index.even? ? 'even-row' : 'odd-row' %>">
                            <td><%= user.email %></td>
                            <td><%= user.phone_number %></td>
                            <td><%= user.classification&.name %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            </div>
        </div>
    </div>
    <!-- Upcoming Events Section -->
<div class="section events-section">
    <h2>Upcoming Events</h2>
    <div class="event-buttons">
        <%= link_to "Add Event", events_new_path, class: "add-event-button" %>
        <%= link_to "Add Final Countdown Event", new_final_countdown_event_path, class: "add-event-button" %>
    </div>
    <div class="scrollable-table">
        <table class="events-table">
            <thead>
                <tr>
                    <th>Event Name</th>
                    <th>Date</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <% upcoming_events = @events.select { |event| event.date.present? && event.date >= Date.today } %>
                <% if upcoming_events.any? %>
                    <% upcoming_events.each do |event| %>
                        <tr class="<%= 'final-countdown-event' if event.hasCountdown %>">
                            <td><%= event.name %></td>
                            <td><%= event.date.present? ? event.date.strftime('%B %d, %Y') : "Date not set" %></td>
                            <td>
                                <%= form_with url: event_path(event), method: :delete, class: 'delete-form' do %>
                                    <%= button_tag type: 'submit', class: 'delete-button', data: { confirm: "Are you sure you want to delete the #{event.name} event?" } do %>
                                    <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#ffffff}</style><path d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"/></svg>
                                    <% end %>
                                <% end %>
                                <div class="dropdown">
                                    <button class="dropdown-button">
                                    <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 640 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#ffffff}</style><path d="M144 0a80 80 0 1 1 0 160A80 80 0 1 1 144 0zM512 0a80 80 0 1 1 0 160A80 80 0 1 1 512 0zM0 298.7C0 239.8 47.8 192 106.7 192h42.7c15.9 0 31 3.5 44.6 9.7c-1.3 7.2-1.9 14.7-1.9 22.3c0 38.2 16.8 72.5 43.3 96c-.2 0-.4 0-.7 0H21.3C9.6 320 0 310.4 0 298.7zM405.3 320c-.2 0-.4 0-.7 0c26.6-23.5 43.3-57.8 43.3-96c0-7.6-.7-15-1.9-22.3c13.6-6.3 28.7-9.7 44.6-9.7h42.7C592.2 192 640 239.8 640 298.7c0 11.8-9.6 21.3-21.3 21.3H405.3zM224 224a96 96 0 1 1 192 0 96 96 0 1 1 -192 0zM128 485.3C128 411.7 187.7 352 261.3 352H378.7C452.3 352 512 411.7 512 485.3c0 14.7-11.9 26.7-26.7 26.7H154.7c-14.7 0-26.7-11.9-26.7-26.7z"/></svg>
                                    </button>
                                    <div class="dropdown-content">
                                        <% if event.users.any? %>
                                            <a class="static-item" href="#">Attendance</a>
                                            <% event.users.each do |user| %>
                                                <a href="#"><%= user.first_name + " " + user.last_name %></a>
                                            <% end %>
                                        <% else %>
                                            <a class="static-item" href="#">Attendance</a>
                                            <a class="static-item-no-attendance" href="#">No users have checked in to this event.</a>
                                        <% end %>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    <% end %>
                <% else %>
                    <tr>
                        <td colspan="3">No upcoming events.</td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
    <div class="event-item">
        <%= link_to events_path, class: "view-all-events-button" do %>
        <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com/ License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M0 96C0 78.3 14.3 64 32 64H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 128 0 113.7 0 96zM0 256c0-17.7 14.3-32 32-32H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32zM448 416c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32z"/></svg>
        View All Events
        <% end %>
    </div>
</div>

      
</div>
</header>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Get all delete buttons with a data-confirm attribute
        const deleteButtons = document.querySelectorAll('.delete-button[data-confirm]');

        // Function to handle the click event on delete buttons
        function handleDeleteButtonClick(event) {
            const confirmationMessage = event.currentTarget.getAttribute('data-confirm');
            const isConfirmed = confirm(confirmationMessage);

            if (!isConfirmed) {
                event.preventDefault(); // Prevent the default action (deleting the event)
            }
        }

        // Add a click event listener to each delete button
        deleteButtons.forEach((button) => {
            button.addEventListener('click', handleDeleteButtonClick);
        });
    });
</script>
</body>
</html>

app/views/users/events_attended.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="<%= asset_path('events_attended.css') %>">
    <link rel="stylesheet" type="text/css" href="<%= asset_path('user_dash.css') %>">
    <link rel="stylesheet" type="text/css" href="<%= asset_path('flash_alert.css') %>">
    <title>Events Attended</title>
  </head>
  <body>
  <% if flash[:alert].present? %>
  <div class="alert alert-alert">
      <%= flash[:alert] %>
  </div>
<% end %>
    <header>
    <img src="<%= asset_path('IMG_6562.png') %>" alt="logo" class="logo">
<p class="title">Volunteers Around the World</p>
      <div class="container">


          <nav>
              <ul>
                <li><a href="<%= user_dashboard_path %>">Home</a></li>
                  <li><a href="<%= upcoming_events_path %>">Upcoming Events</a></li>
                  <li><a href="<%= user_checkin_path %>">Check In</a></li>
              </ul>
          </nav>
          <%= link_to "Log Out", logout_path, class: "logout-button" %>

      </div>
    </header>
    <div class="container_events">
      <div class="split-container">
        <div class="list-container">
          <h2>Events Attended by <%= current_user_name %></h2>
          <ul class="events-list">
            <% if @attended_events.present? %>
              <% @attended_events.each do |event| %>
                <%= link_to event_path(event) do %>
                  <li>
                    <%= event.name %>
                  </li>
                <% end %>
              <% end %>
            <% else %>
              <li>No attended events found.</li>
            <% end %>
          </ul>
        </div>
        <div class="simple-calendar-container">
          <%= month_calendar do |date| %>
            <%= date %>
          <% end %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/users/user_checkin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <link rel="stylesheet" type="text/css" href="<%= asset_path('checkin.css') %>">
    <link rel="stylesheet" type="text/css" href="<%= asset_path('user_dash.css') %>">
    <link rel="stylesheet" type="text/css" href="<%= asset_path('flash_alert.css') %>">
    <title>User Check-In</title>
</head>
<body>

<header>
<img src="<%= asset_path('IMG_6562.png') %>" alt="logo" class="logo">
<p class="title">Volunteers Around the World</p>
<div class="container">


    <nav>
        <ul>
            <li><a href="<%= user_dashboard_path %>">Home</a></li>
            <li><a href="<%= upcoming_events_path %>">Upcoming Events</a></li>
            <li><a href="<%= events_attended_path %>">Events Attended</a></li>
        </ul>
    </nav>
    <%= link_to "Log Out", logout_path, class: "logout-button" %>

</div>
</header>


<div class="section">
    <h2>Check-In for Event</h2>
    <%= form_with model: @user, url: user_checkin_path(@user), method: :post do |f| %>
        <div class="form-group">
            <%= f.label :event_id, 'Select Event' %>
            <%= f.collection_select :event_id, Event.all, :id, :name, prompt: 'Select an Event' %>
        </div>
        <div class="form-group">
            <%= f.label :phone_number, 'Verify Phone Number' %>
            <%= f.text_field :phone_number, class: 'form-control' %>
        </div>
        <%= f.submit "Check-In" %>
        
    <% end %>
</div>

</body>
</html>

app/views/users/user_dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="<%= asset_path('user_dash.css') %>">
    <link rel="stylesheet" type="text/css" href="<%= asset_path('countdown.css') %>">
    <link rel="stylesheet" type="text/css" href="<%= asset_path('flash_alert.css') %>">
    <title>User Dashboard</title>
</head>
<body>
    <% flash.each do |type, message| %>
        <div class="flash-message <%= type %>">
        <%= message %>
        </div>
    <% end %>
    <header>


    <img src="<%= asset_path('IMG_6562.png') %>" alt="logo" class="logo">
    <p class="title">Volunteers Around the World</p>
    <div class="container">
       
        <nav>
            <ul>
                <li><a href="<%= upcoming_events_path %>">Upcoming Events</a></li>
                <li><a href="<%= events_attended_path %>">Events Attended</a></li>
                <li><a href="<%= user_checkin_path %>">Check In</a></li>
                <% if @current_user && @current_user.isAdmin? %>
                    <li><%= link_to "Admin Dashboard", admin_dashboard_path, class: "user-button" %></li>
                <% end %>
            </ul>
        </nav>
        <%= link_to "Log Out", logout_path, class: "logout-button" %>
    </div>
</header>

<div class="countdown-container">
    <div class="countdown-header">
        <h1>
            <span class="final-word">FINAL</span>
            <span class="event-word">EVENT</span>
            <span class="countdown-word">COUNTDOWN</span>
        </h1>
    </div>

    <div class="countdown" data-final-countdown-date="<%= @final_countdown_date %>">
        <div class="countdown-item">
            <span class="days-label">Days</span>
            <span class="days"></span>
        </div>
        <div class="countdown-item">
            <span class="hours-label">Hours</span>
            <span class="hours"></span>
        </div>
        <div class="countdown-item">
            <span class="minutes-label">Minutes</span>
            <span class="minutes"></span>
        </div>
    </div>
</div>

<%= javascript_include_tag 'countdown' %>
</body>
</html>