config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Root route
  root 'users#home'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'logout', to: 'devise/sessions#destroy'
  end
  # Admin dashboard route
  get 'admin_dashboard', to: 'users#admin_dashboard', as: 'admin_dashboard'
  get 'user_dashboard', to: 'users#user_dashboard', as: 'user_dashboard'
  get 'admin_checkin', to: 'users#admin_checkin', as: 'admin_checkin'
  get 'user_checkin', to: 'users#user_checkin', as: 'user_checkin'
  post 'admin_checkin', to: 'users#admin_checkin'
  post 'user_checkin', to: 'users#checkin'
  post 'add_admin', to: 'users#add_admin', as: 'admin_add_admin'
  get '/users/home', to: 'users#home', as: 'users_home'
  get '/events/index', to: 'events#index', as: 'events_index'
  get '/events/new', to: 'events#new', as: 'events_new'

  get 'profile_setup', to: 'users#profile_setup'
  post 'create_profile', to: 'users#create_profile'

  get 'users/events_attended', to: 'users#events_attended', as: 'events_attended'
  get 'users/upcoming_events', to: 'users#upcoming_events', as: 'upcoming_events'

  # Users routes
  resources :users, except: :show do
    collection do
      put :grant_admin
      get 'profile_setup'
      post 'create_profile'
    end

    member do
      post 'checkin'
    end
    post 'add_admin', on: :collection
  end

  # Events routes
  resources :events, only: %i[index new create destroy]

  # Routes for Final Countdown Event
  get 'events/new_final_countdown', to: 'events#new_final_countdown', as: 'new_final_countdown_event'
  post 'events/create_final_countdown', to: 'events#create_final_countdown', as: 'create_final_countdown_event'
  resources :events, only: %i[index show new create destroy]
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :events_users
  has_many :users, through: :events_users
  validates :name, presence: true
  validates :date, presence: true
  validates_inclusion_of :hasCountdown, in: [true, false]
end

app/controllers/events_controller.rb
# frozen_string_literal: true

# The EventsController is responsible for managing events within the application.
# It provides actions to list events, create new events, and delete existing events.
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new(hasCountdown: false)
  end

  def create
    @event = Event.new(event_params.merge(hasCountdown: false))

    if @event.save
      redirect_to events_path, notice: 'Event created successfully.'
    else
      render :new
    end
  end

  def new_final_countdown
    @event = Event.new(hasCountdown: true)
  end

  def create_final_countdown
    # Delete all prior final countdown events
    Event.where(hasCountdown: true).destroy_all

    @event = Event.new(event_params.merge(hasCountdown: true))

    if @event.save
      redirect_to events_path, notice: 'Final Countdown Event created successfully.'
    else
      render :new_final_countdown
    end
  end

  def show
    @event = Event.find(params[:id])
    # You can add any logic related to displaying an individual event here.
  end

  def destroy
    @event = Event.find(params[:id])

    # Remove all associated entries in events_users before deleting the event
    @event.users.clear

    @event.destroy
    redirect_to request.referrer || admin_dashboard_path, notice: 'Event was successfully deleted.'
  end

  private

  def event_params
    params.require(:event).permit(:name, :date)
  end
end

app/views/events/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Your Page Title</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f1efee;
      margin: 0;
      padding: 0;
    }

    .container {
      background-color: white;
      padding: 20px;
      border-radius: 10px;
      margin: 20px;
      display: flex;
      flex-direction: column;
      align-items: center;
      height: 80vh;
    }

    h1 {
      margin-bottom: 20px;
    }

    .back-link {
      background-color: #5a9bec;
      color: white;
      padding: 10px 15px; /* Padding inside the buttons */
      border-radius: 5px; /* Rounded corners for buttons */
      text-decoration: none; /* Remove underline from links */
      display: inline-block; /* Align buttons side by side */
      margin-top: 20px; 
      text-align: center;
      cursor: pointer;
      display: block; 
    }
    
    .split-container {
      display: flex;
      width: 100%;
    }

    .split-container > * {
      flex: 1;
      padding: 10px;
      max-width: 50%;
    }

    .list-container {
      max-height: 80%;
      overflow-y: auto;
      border-radius: 10px;
      border: 1px solid #ccc; /* Add border */
      margin: 5px;
      background-color: #f1efee;
    }

    ul {
      list-style: none;
      padding: 0;
      margin: 0;
    }

    li {
      margin: 5px;
      display: flex;
      align-items: center;
      border: 1px solid #ccc;
      padding: 10px;
      background-color: white;
    }

    .event-name {
      flex: 1;
    }

    .event-date {
      flex-shrink: 0;
      width: 80px;
      text-align: center;
      overflow: hidden;
      white-space: nowrap;
      text-overflow: ellipsis;
    }

    .alert.alert-alert {
      background-color: #f44336; /* Red background color */
      color: white; /* White text color */
      padding: 10px;
      border-radius: 4px;
    }

    /* .simple-calendar styles */
.simple-calendar {
  background-color: white;
  border: 1px solid #ccc;
  border-radius: 10px;
  padding: 12px;
  display: inline-block;
  margin: 1px;
  
}

.simple-calendar .day.has-events {
  background-color: white; /* Set the background color for days with events to white */
}


.simple-calendar .prev-month {
  color: gray;
  border: 1px solid gray;
}
.simple-calendar .next-month {
  color:  gray;
  border: 1px solid gray;
}
.simple-calendar .current-month {
  border: 2px solid black;
  padding: 4px;
  height: 4vh;
  margin: 0;
}

.calendar-title {
  font-weight: bold;
  margin: 0 25%; 
}

.simple-calendar a{
  border-radius: 8px;
  padding: 6px;
  background-color: #500000;
  color: white;
}

.calendar-heading {
  margin-bottom: 5%;
}
  </style>

</head>
<body>
<% flash.each do |type, message| %>
  <div class="flash-message <%= type %>">
  <%= message %>
  </div>
<% end %>
  <div class="container">
    <h1>All Events</h1>
    <div class="split-container">
      <div class="list-container">
        <strong>Upcoming Events</strong>
        <ul>
          <% @events.each do |event| %>
            <% if event.date >= Date.today %>
              <li>
                <span class="event-name"><%= event.name %></span>
                <span class="event-date"><%= event.date.strftime('%b %d') %></span> <!-- Shortened date format -->
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <div class="list-container">
        <strong>Past Events</strong>
        <ul>
          <% @events.each do |event| %>
            <% if event.date < Date.today %>
              <li>
                <span class="event-name"><%= event.name %></span>
                <span class="event-date"><%= event.date.strftime('%b %d') %></span> <!-- Shortened date format -->
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <!-- Month Calendar code here -->
      <div class="simple-calendar-container">
        <%= month_calendar events: @events do |date, events| %>
          <div class="simple-calendar <%= 'has-events' if events.present? %>">
            <%= date.strftime('%b %d') %> <!-- Shortened date format -->
            <% events.each do |event| %>
              <div>
                <%= event.name %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="back-link">
      <%= link_to "Back to Admin Dashboard", admin_dashboard_path %>
    </div>
  </div>
</body>
</html>

app/views/events/new.html.erb
<!DOCTYPE html>
<html>
<head>

  <style>
    body {
      background-color: #f1efee;
      margin: 0;
      padding: 0;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh; 
    }

    .container {
      background-color: white;
      padding: 20px;
      border-radius: 10px;
      margin: 20px;
      width: 80%; 
      max-width: 600px; 
    }

    h1, form {
      margin-bottom: 20px; 
    }

    .field {
      margin-bottom: 10px; 
      margin-right: 10px;
    }

    label {
      display: block; 
    }

    input[type="text"],
    input[type="date"] {
      width: 100%; 
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 5px;
    }

    .actions {
      text-align: center;
    }

    .submit-button {
      background-color: green;
      color: white;
      padding: 10px 20px;
      border: none;
      border-radius: 5px;
      cursor: pointer;
    }

    .back-link {
      background-color: #5a9bec;
      color: white;
      padding: 10px 15px; /* Padding inside the buttons */
      border-radius: 5px; /* Rounded corners for buttons */
      text-decoration: none; /* Remove underline from links */
      display: inline-block; /* Align buttons side by side */
      margin-top: 20px; 
      text-align: center;
      cursor: pointer;
      display: block; 
    }

    .alert.alert-alert {
      background-color: #f44336; /* Red background color */
      color: white; /* White text color */
      padding: 10px;
      border-radius: 4px;
    }

  </style>
</head>
<body>
<% if flash[:alert].present? %>
            <div class="alert alert-alert">
                <%= flash[:alert] %>
            </div>
        <% end %>
  <div class="container">
    <h1>Create a New Event</h1>

    <%= form_with(model: @event, url: events_path, method: :post) do |form| %>
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label :date %>
        <%= form.date_field :date %>
      </div>

      <div class="actions">
        <%= form.submit "Create Event", class: "submit-button" %>
      </div>
    <% end %>

    <div class="back-link">
      <%= link_to "Back to Admin Dashboard", admin_dashboard_path %>
    </div>
  </div>
</body>
</html>

app/views/events/new_final_countdown.html.erb
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      background-color: #f1efee;
      margin: 0;
      padding: 0;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh; 
    }

    .container {
      background-color: white;
      padding: 20px;
      border-radius: 10px;
      margin: 20px;
      width: 80%; 
      max-width: 600px; 
    }

    h1, form {
      margin-bottom: 20px; 
    }

    .field {
      margin-bottom: 10px; 
      margin-right: 10px;
    }

    label {
      display: block; 
    }

    input[type="text"],
    input[type="date"] {
      width: 100%; 
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 5px;
    }

    .actions {
      text-align: center;
    }

    .submit-button {
      background-color: green;
      color: white;
      padding: 10px 20px;
      border: none;
      border-radius: 5px;
      cursor: pointer;
    }

    .back-link {
      background-color: #5a9bec;
      color: white;
      padding: 10px 15px; /* Padding inside the buttons */
      border-radius: 5px; /* Rounded corners for buttons */
      text-decoration: none; /* Remove underline from links */
      display: inline-block; /* Align buttons side by side */
      margin-top: 20px; 
      text-align: center;
      cursor: pointer;
      display: block; 
    }

    .alert.alert-alert {
      background-color: #f44336; /* Red background color */
      color: white; /* White text color */
      padding: 10px;
      border-radius: 4px;
    }
    
  </style>
</head>
<body>
<% flash.each do |type, message| %>
  <div class="flash-message <%= type %>">
  <%= message %>
  </div>
<% end %>
  <div class="container">
    <h1>Create a Final Countdown Event</h1>

    <%= form_with(model: @event, url: create_final_countdown_event_path, method: :post) do |form| %>
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label :date %>
        <%= form.date_field :date %>
      </div>

      <div class="actions">
        <%= form.submit "Create Final Countdown Event", class: "submit-button" %>
      </div>
    <% end %>

    <div class="back-link">
      <%= link_to "Back to Admin Dashboard", admin_dashboard_path %>
    </div>
  </div>
</body>
</html>

app/views/events/show.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="<%= asset_path('view_events.css') %>">
<link rel="stylesheet" type="text/css" href="<%= asset_path('flash_alert.css') %>">
</head>
<body>
<% if flash[:alert].present? %>
            <div class="alert alert-alert">
                <%= flash[:alert] %>
            </div>
        <% end %>
    <div class="container">
        <%= link_to 'Back', events_attended_path, class: 'back-button' %>
        <div class="card">
            <div class="title"><%= @event.name %></div>
            <p class="date">Occurred: <%= @event.date %></p>
        </div>
    </div>
</body>
</html>